-- Update ket_barang (deskripsi produk) untuk 30 produk pilot
-- Jalankan di tab SQL phpMyAdmin pada database `berlian`
-- Aman dijalankan langsung ke database live, hanya mengubah kolom ket_barang

UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nIbuprofen 200 mg/ 5 ml<br />\r\nIndikasi :<br />\r\nAnti Inflamasi dan Antipiretik. Meredakan nyeri dan demam<br />\r\nEfek Samping :<br />\r\nDapat mengiritasi lambung<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Anak 8-12 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak 3-7 tahun: &frac12; sendok takar (2,5 ml), 3 kali sehari, atau sesuai petunjuk dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 3;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Dextromethorphan HBr 7,5 mg, Pseudoephedrine HCl 15 mg, Chlorphenamine Maleate 0,5 mg<br />\r\nIndikasi :<br />\r\nMeredakan batuk kering, pilek, dan bersin-bersin<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Anak 2-5 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak 6-12 tahun: 2 sendok takar (10 ml), 3 kali sehari<br />\r\n&nbsp;</p>' WHERE `id_barang` = 4;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Paracetamol 120 mg, Pseudoephedrine HCl 7,5 mg, Chlorpheniramine Maleate 0,5 mg, Glyceryl Guaiacolate 50 mg<br />\r\nIndikasi :<br />\r\nMeredakan demam, hidung tersumbat, bersin-bersin, dan batuk berdahak<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Anak 2-5 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak 6-12 tahun: 2 sendok takar (10 ml), 3 kali sehari. Jangan digunakan bersamaan dengan obat penurun panas/paracetamol lain agar tidak overdosis<br />\r\n&nbsp;</p>' WHERE `id_barang` = 5;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap tablet mengandung Kalsium 250 mg (setara Kalsium Karbonat 675 mg), Vitamin C 1000 mg, Vitamin D 300 IU, Vitamin B6 HCl 15 mg<br />\r\nIndikasi :<br />\r\nMembantu memenuhi kebutuhan kalsium dan vitamin harian, menjaga kesehatan tulang dan daya tahan tubuh<br />\r\nEfek Samping :<br />\r\nDapat mengiritasi lambung. Bila dikonsumsi melebihi dosis anjuran berisiko hiperkalsemia (mual, muntah, lemas)<br />\r\nAturan Pakai :<br />\r\n1 tablet effervescent dilarutkan dalam segelas air, diminum 1 kali sehari atau sesuai petunjuk dokter. Sebaiknya diminum saat perut sudah terisi makanan<br />\r\n&nbsp;</p>' WHERE `id_barang` = 11;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nPermetrin 1%<br />\r\nIndikasi :<br />\r\nMengatasi infeksi kutu rambut (pedikulosis)<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan iritasi kulit kepala ringan seperti rasa gatal, perih, atau kemerahan<br />\r\nAturan Pakai :<br />\r\nOleskan secukupnya pada rambut dan kulit kepala yang kering, diamkan sesuai petunjuk kemasan lalu bilas. Bila setelah 7 hari masih ditemukan kutu hidup, pengobatan dapat diulang (maksimal 2 kali dalam 2 minggu)<br />\r\n&nbsp;</p>' WHERE `id_barang` = 13;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nBalsam Peru 2%, Zinc Oxide 3,5%, Precipitated Sulfur 1,42%, Salicylic Acid 0,8%, Camphor 0,31%, Menthol 0,47%, Talkum ad 100%<br />\r\nIndikasi :<br />\r\nMeredakan biang keringat dan gatal-gatal pada kulit, menjaga kulit tetap kering, serta membantu mengurangi bau badan<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan iritasi pada kulit yang sensitif<br />\r\nAturan Pakai :<br />\r\nTaburkan dan ratakan pada bagian kulit yang gatal atau terkena biang keringat, beberapa kali sehari sesuai kebutuhan, sebaiknya setelah mandi. Hindari pemakaian pada kulit melepuh, berair, atau luka terbuka<br />\r\n&nbsp;</p>' WHERE `id_barang` = 14;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nPovidone-Iodine 1%<br />\r\nIndikasi :<br />\r\nMengatasi sakit tenggorokan, gusi bengkak, sariawan, bau mulut, serta menjaga kebersihan mulut pasca operasi<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan rasa perih ringan di mulut/tenggorokan; jarang, reaksi alergi terhadap iodine<br />\r\nAturan Pakai :<br />\r\nTuang 12-16 ml cairan ke tutup botol/gelas takar, kumur selama 30 detik lalu buang, dapat digunakan 3-5 kali sehari. Hindari makan/minum selama 15-30 menit setelah pemakaian<br />\r\n&nbsp;</p>' WHERE `id_barang` = 15;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nAsam Salisilat 2%, Talkum<br />\r\nIndikasi :<br />\r\nMeredakan gatal-gatal dan biang keringat, serta menjaga kulit tetap kering<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan rasa panas seperti terbakar atau kemerahan pada kulit yang sensitif<br />\r\nAturan Pakai :<br />\r\nGunakan setelah mandi, taburkan secukupnya pada area kulit yang bermasalah, 2-3 kali sehari<br />\r\n&nbsp;</p>' WHERE `id_barang` = 16;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nMinyak Kelapa, Minyak Kayu Putih, Minyak Sereh, Daun Lada, Rimpang Jahe, Rimpang Kunyit, Bawang Merah<br />\r\nIndikasi :<br />\r\nMeredakan nyeri otot dan sendi, masalah kulit ringan, serta gangguan pencernaan dan pernapasan ringan<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan rasa perih bila digunakan langsung dengan tangan kosong pada luka terbuka<br />\r\nAturan Pakai :<br />\r\nGunakan 2-3 kali sehari atau sesuai kebutuhan. Untuk luka lecet/gores kecil, gunakan kapas atau cotton bud yang telah ditetesi minyak, hindari kontak langsung dengan tangan kosong<br />\r\n&nbsp;</p>' WHERE `id_barang` = 17;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nMinyak Kelapa, Minyak Kayu Putih, Minyak Sereh, Daun Lada, Rimpang Jahe, Rimpang Kunyit, Bawang Merah<br />\r\nIndikasi :<br />\r\nMeredakan nyeri otot dan sendi, masalah kulit ringan, serta gangguan pencernaan dan pernapasan ringan<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan rasa perih bila digunakan langsung dengan tangan kosong pada luka terbuka<br />\r\nAturan Pakai :<br />\r\nGunakan 2-3 kali sehari atau sesuai kebutuhan. Untuk luka lecet/gores kecil, gunakan kapas atau cotton bud yang telah ditetesi minyak, hindari kontak langsung dengan tangan kosong<br />\r\n&nbsp;</p>' WHERE `id_barang` = 18;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nAllopurinol 100 mg<br />\r\nIndikasi :<br />\r\nMenurunkan kadar asam urat dalam darah<br />\r\nEfek Samping :<br />\r\nDapat mengiritasi lambung; jarang, reaksi alergi pada kulit (ruam)<br />\r\nAturan Pakai :<br />\r\nDiminum 1 kali sehari setelah makan, disertai banyak minum air putih. Jangan menghentikan penggunaan tanpa saran dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 19;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nDexamethasone 0,5 mg, Dexchlorpheniramine Maleate 2 mg<br />\r\nIndikasi :<br />\r\nMeredakan gejala alergi yang disertai peradangan<br />\r\nEfek Samping :<br />\r\nMenyebabkan kantuk yang cukup kuat; dapat mengiritasi lambung<br />\r\nAturan Pakai :<br />\r\nDiminum 3 kali sehari 1 tablet setelah makan, atau sesuai petunjuk dokter. Hindari mengemudi atau mengoperasikan mesin setelah minum obat ini<br />\r\n&nbsp;</p>' WHERE `id_barang` = 21;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nCetirizine HCl 10 mg<br />\r\nIndikasi :<br />\r\nMeredakan gejala alergi dan biduran (urtikaria)<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk; dapat mengiritasi lambung<br />\r\nAturan Pakai :<br />\r\n1 kapsul diminum 1 kali sehari, sesudah makan. Hindari mengemudi atau mengoperasikan mesin setelah mengonsumsi obat ini<br />\r\n&nbsp;</p>' WHERE `id_barang` = 22;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nFluocinolone Acetonide 0,025%, Gentamicin Sulfate 0,1%<br />\r\nIndikasi :<br />\r\nMengobati eksim, gatal-gatal, dan kemerahan pada kulit yang disertai infeksi bakteri<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan iritasi atau rasa terbakar; penipisan kulit bila digunakan jangka panjang<br />\r\nAturan Pakai :<br />\r\nOleskan tipis 2-3 kali sehari hanya pada bagian kulit yang sakit<br />\r\n&nbsp;</p>' WHERE `id_barang` = 23;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nParacetamol 500 mg<br />\r\nIndikasi :<br />\r\nMeredakan demam dan nyeri ringan hingga sedang<br />\r\nEfek Samping :<br />\r\nJarang; dapat mengiritasi lambung atau menyebabkan reaksi alergi bila digunakan berlebihan<br />\r\nAturan Pakai :<br />\r\nDiminum 1 tablet, 3-4 kali sehari setelah makan, atau sesuai petunjuk dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 24;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Aluminium Hidroksida 200 mg, Magnesium Hidroksida 200 mg, Simethicone 20 mg<br />\r\nIndikasi :<br />\r\nMengatasi kelebihan asam lambung, kembung, dan gangguan pencernaan<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan diare (efek magnesium) atau konstipasi (efek aluminium) bila digunakan berlebihan<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Diminum 3-4 kali sehari, 1 jam sebelum makan<br />\r\n&nbsp;</p>' WHERE `id_barang` = 25;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nAmoxicillin 500 mg<br />\r\nIndikasi :<br />\r\nAntibiotik untuk mengatasi infeksi bakteri seperti ISPA, ISK, infeksi kulit, dan infeksi gigi<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan mual, diare, atau kram perut<br />\r\nAturan Pakai :<br />\r\nDiminum 3 kali sehari 1 tablet setelah makan, dihabiskan sesuai resep dokter agar tidak terjadi resistensi antibiotik<br />\r\n&nbsp;</p>' WHERE `id_barang` = 26;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nMinyak Kelapa, Minyak Kayu Putih, Minyak Sereh, Daun Lada, Rimpang Jahe, Rimpang Kunyit, Bawang Merah<br />\r\nIndikasi :<br />\r\nMeredakan nyeri otot dan sendi, masalah kulit ringan, serta gangguan pencernaan dan pernapasan ringan<br />\r\nEfek Samping :<br />\r\nDapat menimbulkan rasa perih bila digunakan langsung dengan tangan kosong pada luka terbuka<br />\r\nAturan Pakai :<br />\r\nGunakan 2-3 kali sehari atau sesuai kebutuhan. Untuk luka lecet/gores kecil, gunakan kapas atau cotton bud yang telah ditetesi minyak, hindari kontak langsung dengan tangan kosong<br />\r\n&nbsp;</p>' WHERE `id_barang` = 28;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Paracetamol 120 mg, Pseudoephedrine HCl 7,5 mg, Glyceryl Guaiacolate 50 mg, Chlorpheniramine Maleate 0,5 mg<br />\r\nIndikasi :<br />\r\nMeredakan demam, sakit kepala, hidung tersumbat, bersin-bersin, dan batuk<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Anak 2-5 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak 6-12 tahun: 2 sendok takar (10 ml), 3 kali sehari. Sudah mengandung paracetamol, jangan dikombinasikan dengan obat penurun panas lain<br />\r\n&nbsp;</p>' WHERE `id_barang` = 29;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nDistilled Witch Hazel 0,3%, Tocopheryl Acetate (Vitamin E), Benzalkonium Chloride 0,002%<br />\r\nIndikasi :<br />\r\nMembersihkan mata dari kotoran, meredakan iritasi ringan, dan menyegarkan mata lelah<br />\r\nEfek Samping :<br />\r\nJarang; dapat menimbulkan rasa perih ringan atau kemerahan sementara pada mata yang sensitif<br />\r\nAturan Pakai :<br />\r\nGunakan 3-4 kali sehari atau sesuai kebutuhan. Jika gejala tidak membaik dalam 2-3 hari, konsultasikan ke dokter mata<br />\r\n&nbsp;</p>' WHERE `id_barang` = 30;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Dextromethorphan HBr 7,5 mg, Diphenhydramine HCl 12,5 mg, dengan Peppermint Oil dan Etanol<br />\r\nIndikasi :<br />\r\nMeredakan batuk tidak berdahak (batuk kering)<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk<br />\r\nAturan Pakai :<br />\r\nDewasa dan anak &gt;12 tahun: 10 ml, 3 kali sehari. Anak 6-12 tahun: 5 ml, 3 kali sehari. Hindari mengemudi atau mengoperasikan mesin setelah minum obat ini<br />\r\n&nbsp;</p>' WHERE `id_barang` = 31;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nTiap 5 ml mengandung Paracetamol 120 mg, Pseudoephedrine HCl 7,5 mg, Guaifenesin 50 mg, Chlorpheniramine Maleate 0,5 mg<br />\r\nIndikasi :<br />\r\nMeredakan gejala flu yang disertai batuk berdahak<br />\r\nEfek Samping :<br />\r\nDapat menyebabkan kantuk<br />\r\nAturan Pakai :<br />\r\nKocok dahulu sebelum dituang. Anak 2-5 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak 6-12 tahun: 2 sendok takar (10 ml), 3 kali sehari. Sudah mengandung paracetamol, jangan dikombinasikan dengan obat penurun panas lain<br />\r\n&nbsp;</p>' WHERE `id_barang` = 32;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nClopidogrel Bisulfate setara Clopidogrel 75 mg<br />\r\nIndikasi :<br />\r\nMencegah penggumpalan darah yang dapat menyebabkan penyumbatan pembuluh darah, serangan jantung, stroke iskemik, dan penyakit arteri perifer<br />\r\nEfek Samping :<br />\r\nPerdarahan (mudah memar dan mimisan), pusing, diare, dan gangguan pencernaan<br />\r\nAturan Pakai :<br />\r\nDiminum 1 kali sehari, sebelum atau sesudah makan, atau sesuai resep dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 199;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nAzithromycin 500 mg<br />\r\nIndikasi :<br />\r\nAntibiotik untuk mengatasi infeksi bakteri pada saluran napas, telinga, kulit, serta infeksi menular seksual seperti klamidia<br />\r\nEfek Samping :<br />\r\nMual, muntah, sakit perut, diare, dan pusing<br />\r\nAturan Pakai :<br />\r\nDiminum sesuai resep dokter, idealnya 1-2 jam sebelum atau sesudah makan, pada waktu yang sama setiap hari<br />\r\n&nbsp;</p>' WHERE `id_barang` = 201;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nClindamycin 300 mg<br />\r\nIndikasi :<br />\r\nAntibiotik untuk mengatasi infeksi bakteri serius, termasuk infeksi kulit, tulang, sendi, dan saluran pernapasan<br />\r\nEfek Samping :<br />\r\nMual, muntah, diare, serta rasa seperti logam di mulut<br />\r\nAturan Pakai :<br />\r\nDiminum sesuai resep dokter (umumnya tiap 6-8 jam), dihabiskan meski gejala sudah membaik agar tidak terjadi resistensi bakteri<br />\r\n&nbsp;</p>' WHERE `id_barang` = 203;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nNatrium Diklofenak (Diclofenac Sodium) 50 mg<br />\r\nIndikasi :<br />\r\nMeredakan nyeri akibat peradangan sendi (artritis), cedera, nyeri pascaoperasi, atau nyeri akut lainnya<br />\r\nEfek Samping :<br />\r\nSakit perut atau maag, tekanan darah meningkat; jarang, gangguan fungsi hati/ginjal<br />\r\nAturan Pakai :<br />\r\nDiminum tiap 8 jam setelah makan, ditelan utuh dengan segelas air, atau sesuai resep dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 204;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nIsosorbide Dinitrate 5 mg<br />\r\nIndikasi :<br />\r\nMencegah dan meredakan angina (nyeri dada) akibat penyakit jantung koroner<br />\r\nEfek Samping :<br />\r\nSakit kepala, pusing, dan tekanan darah rendah (hipotensi)<br />\r\nAturan Pakai :<br />\r\nDiletakkan di bawah lidah (sublingual) dan dibiarkan larut untuk serangan akut, atau diminum dengan air sebelum makan tiap 8-12 jam sesuai resep dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 205;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nMupirocin 2%<br />\r\nIndikasi :<br />\r\nMengobati infeksi bakteri pada kulit, seperti impetigo<br />\r\nEfek Samping :<br />\r\nKulit terasa terbakar, kering, gatal, kemerahan, atau nyeri saat disentuh<br />\r\nAturan Pakai :<br />\r\nOleskan tipis pada area yang terinfeksi 3 kali sehari, maksimal selama 10 hari<br />\r\n&nbsp;</p>' WHERE `id_barang` = 206;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nPantoprazole 40 mg<br />\r\nIndikasi :<br />\r\nMeredakan gejala akibat asam lambung berlebih seperti nyeri perut dan heartburn, serta tukak lambung dan GERD<br />\r\nEfek Samping :<br />\r\nSakit kepala, kembung, diare atau konstipasi, gangguan tidur<br />\r\nAturan Pakai :<br />\r\nDiminum 1 kali sehari (20-40 mg) sebelum makan, ditelan utuh dengan segelas air, atau sesuai resep dokter<br />\r\n&nbsp;</p>' WHERE `id_barang` = 207;
UPDATE `barang` SET `ket_barang` = '<p>Komposisi :<br />\r\nGlucosamine HCl 500 mg<br />\r\nIndikasi :<br />\r\nMembantu memelihara kesehatan dan kelenturan sendi<br />\r\nEfek Samping :<br />\r\nUmumnya aman; jarang dapat menimbulkan gangguan pencernaan ringan atau reaksi alergi (terutama bagi yang alergi kerang/udang, karena bersumber dari cangkang udang)<br />\r\nAturan Pakai :<br />\r\nDiminum 1 tablet, 3 kali sehari, setelah makan, atau sesuai petunjuk pada kemasan<br />\r\n&nbsp;</p>' WHERE `id_barang` = 208;
